mqtt:
  host: 192.168.85.200
  port: 1883
  frequency_topic: haudi/hass/tvoLOM7XjOKcnaosDRb_mw/Ecourt/reverse_mode

modbus:
  host: 192.168.85.202
  port: 502
  frequency_topic: haudi/hass/tvoLOM7XjOKcnaosDRb_mw/Ecourt/reverse_mode